version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-reservation
      MYSQL_USER: db-reservation
      MYSQL_PASSWORD: db-reservation
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reservation_app
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://db-reservation:db-reservation@db:3306/db-reservation
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
